name: UnitTest
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  unitests:
    strategy:
      matrix:
        go: ['1.16']
        platform: [ ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - run: go mod download
      - name: Test
        run: go test -v ./...
